2025-07-07 14:33:54,027 - main - INFO - ==================================================
2025-07-07 14:33:54,028 - main - INFO - 应用程序启动 - 日志系统初始化完成
2025-07-07 14:33:54,028 - main - INFO - 日志文件路径: D:\pythonProject\generateTestCases\logs\app_20250707_143354.log
2025-07-07 14:33:54,028 - main - INFO - ==================================================
2025-07-07 14:33:54,029 - uvicorn.error - INFO - Started server process [10452]
2025-07-07 14:33:54,030 - uvicorn.error - INFO - Waiting for application startup.
2025-07-07 14:33:54,030 - uvicorn.error - INFO - Application startup complete.
2025-07-07 14:33:54,030 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
2025-07-07 14:33:56,005 - main - INFO - 收到飞书请求，document_id=KExEdM3URoe4JdxRyU6cduwHnZd
2025-07-07 14:33:56,587 - httpx - INFO - HTTP Request: GET https://open.feishu.cn/open-apis/docx/v1/documents/KExEdM3URoe4JdxRyU6cduwHnZd/blocks?limit=100 "HTTP/1.1 200 OK"
2025-07-07 14:33:57,199 - httpx - INFO - HTTP Request: GET https://open.feishu.cn/open-apis/drive/v1/medias/batch_get_tmp_download_url?file_tokens=SZPlbksxNo9q2AxkE3TcDp3gnlb "HTTP/1.1 200 OK"
2025-07-07 14:33:57,686 - httpx - INFO - HTTP Request: GET https://open.feishu.cn/open-apis/drive/v1/medias/batch_get_tmp_download_url?file_tokens=JqINbXfOlofwdHxsaYecenlsnAh "HTTP/1.1 200 OK"
2025-07-07 14:33:58,220 - httpx - INFO - HTTP Request: GET https://open.feishu.cn/open-apis/drive/v1/medias/batch_get_tmp_download_url?file_tokens=ZPq4buihSoeZrCxt6jQcMli8n2f "HTTP/1.1 200 OK"
2025-07-07 14:33:58,837 - httpx - INFO - HTTP Request: GET https://open.feishu.cn/open-apis/drive/v1/medias/batch_get_tmp_download_url?file_tokens=I69ubTn76oLpwRxLIP6cjz0tnWb "HTTP/1.1 200 OK"
2025-07-07 14:33:59,554 - httpx - INFO - HTTP Request: GET https://open.feishu.cn/open-apis/drive/v1/medias/batch_get_tmp_download_url?file_tokens=G7hCbfD1UoCXnwxK0hIcXbqhnPg "HTTP/1.1 200 OK"
2025-07-07 14:34:00,117 - httpx - INFO - HTTP Request: GET https://open.feishu.cn/open-apis/drive/v1/medias/batch_get_tmp_download_url?file_tokens=M5XibpflfokO3Dx25UQcS4zgnVh "HTTP/1.1 200 OK"
2025-07-07 14:34:00,118 - main - INFO - 提取的 PRD 文本:
# B端产品登录功能需求文档范文

### 1.1 功能概述

#### 1.1.1 业务流程图

![image](https://internal-api-drive-stream.feishu.cn/space/api/box/stream/download/authcode/?code=MWMzYjhlYTRiOWUwMjVmMWRkZTMwNDY0NjRjYjQwODVfYWUyNzRhMGRkZTFjYzYxNmYyOGNjOTJiOGVkOGUzMzRfSUQ6NzUyMDQ4MjE0MTQwNzYwODgzNV8xNzUxODcwMDM4OjE3NTE5NTY0MzhfVjM)

#### 1.1.2 功能架构

![image](https://internal-api-drive-stream.feishu.cn/space/api/box/stream/download/authcode/?code=NTYyYzZmYTk5OGQwZTRhMTU4ODNmYWEzNzE2NjAyZGJfNjkxNTEyMGMzMWI0NjE0NDRiNjE5M2Q5YTJmMGE3MGFfSUQ6NzUyMTgwNjA4OTg5MDEwMzI5N18xNzUxODcwMDM5OjE3NTE5NTY0MzlfVjM)

### 1.2 功能说明

#### 1.2.1 账号登录

##### 1.2.1.1 业务流程

用户打开登录网址进入登录页面；

输入登录账号、密码、验证码进行登录；

##### 1.2.1.2 页面原型

![image](https://internal-api-drive-stream.feishu.cn/space/api/box/stream/download/authcode/?code=YjJhYmNmMThkODc2OWM5NDU4OTZkNzdjNmZlNDJlNWVfNjliMjhiMjYxNDc1ZTE1ZjhhNDI2ZGI0ZGFlMjIxNDBfSUQ6NzUyMDQ4MjE0MTE3MjQ5ODQzNV8xNzUxODcwMDM5OjE3NTE5NTY0MzlfVjM)

##### 1.2.1.3 逻辑说明

账号输入框：输入账号后显示清空操作按钮，点击清空按钮清空已输入的账号；

密码输入框：输入密码后显示密码明文查看按钮及清空按钮，鼠标按下明文查看按钮密码明文展示，鼠标松开后密文展示，点击清空按钮清空已输入密码；

验证码：验证码为4位随机的大写英文字母，单击验证码展示区域刷新验证码，验证码有效期为60秒；

所有输入框获取焦点时提示文字消失且边框变为绿色，失去焦点时恢复原状；

【登录】按钮：点击【登录】按钮时依次校验登录账号、密码、验证码，若某一项校验出问题则在对应输入框下方红字提醒用户错误原因，全部校验通过则成功登录并进入系统首页；

【找回密码】按钮：点击【找回密码】按钮跳转至找回密码页面；

账号首次成功登录时弹窗提示账号首次登录时需修改初始密码，点击【确定】按钮跳转至修改初始密码页面，初始密码修改后需要重新输入账号、密码、验证码进行登录；

#### 1.2.2 重置初始密码

##### 1.2.2.1 业务流程

用户初次成功登录账号后弹窗提示用户修改初始密码；

点击弹窗的【确定】按钮后页面跳转至重置初始密码页面；

##### 1.2.2.2 页面原型

![image](https://internal-api-drive-stream.feishu.cn/space/api/box/stream/download/authcode/?code=MDFiZjBlOTEyNDNlNzA2ODMzNmUyM2E3NzE5OTYyMTBfY2U2OTM1YzJlOTk2OGU4MTgyNmZiMTZmZTc0NWUwYWZfSUQ6NzUyMDQ4MjE0MDI2MTgyNjU3OV8xNzUxODcwMDQwOjE3NTE5NTY0NDBfVjM)

##### 1.2.2.3 业务逻辑

新密码输入框：输入密码后显示密码明文查看按钮及清空按钮，鼠标按下明文查看按钮密码明文展示，鼠标松开后密文展示，点击清空按钮清空已输入密码；

确认密码：输入密码后显示密码明文查看按钮及清空按钮，鼠标按下明文查看按钮密码明文展示，鼠标松开后密文展示，点击清空按钮清空已输入密码；

验证码：点击【获取验证码】按钮向登录账号绑定手机号发送6位随机数字验证码，验证码已发送后【获取验证码】按钮展示60秒倒计时，倒计时结束后恢复原状，验证码有效期为60秒；

所有输入框获取焦点时提示文字消失且输入框边框变为绿色，失去焦点时恢复原状；

【取消】按钮：点击【取消】按钮取消修改初始密码，返回至登录页面；

【提交】按钮：点击【提交】按钮依次校验密码、验证码，若某一项校验出问题则在对应输入框下方红字提醒用户错误原因，全部校验通过则提示重置密码成功，然后返回至登录页面；

#### 1.2.3 找回密码

##### 1.2.3.1 业务流程

用户打开登录网址进入登录页面；

忘记登录密码后在登录页面页面点击【找回密码】按钮进入找回密码页面；

##### 1.2.3.2 页面原型

![image](https://internal-api-drive-stream.feishu.cn/space/api/box/stream/download/authcode/?code=ZDAwNWIzY2E4YzQzMjM4NTNjOGRkYzIzMTc1ZTAzMmFfZGRiYmVmMjkzNTY5NWYwMzM3MjM3OTgwODQxYTlhMTZfSUQ6NzUyMDQ4MjEzODAwMjA5NjE1Nl8xNzUxODcwMDQxOjE3NTE5NTY0NDFfVjM)

##### 1.2.3.3 业务逻辑

新密码输入框：输入密码后显示密码明文查看按钮及清空按钮，鼠标按下明文查看按钮密码明文展示，鼠标松开后密文展示，点击清空按钮清空已输入密码；

确认密码：输入密码后显示密码明文查看按钮及清空按钮，鼠标按下明文查看按钮密码明文展示，鼠标松开后密文展示，点击清空按钮清空已输入密码；

验证码：点击【获取验证码】按钮向登录账号绑定手机号发送6位随机数字验证码，验证码已发送后【获取验证码】按钮展示60秒倒计时，倒计时结束后恢复原状，验证码有效期为60秒；

所有输入框获取焦点时提示文字消失且输入框边框变为绿色，失去焦点时恢复原状；

【取消】按钮：点击【取消】按钮取消修改初始密码，返回至登录页面；

【提交】按钮：点击【提交】按钮依次校验密码、验证码，若某一项校验出问题则在对应输入框下方红字提醒用户错误原因，全部校验通过则提示重置密码成功，然后返回至登录页面；

#### 1.2.4 修改密码

##### 1.2.4.1 业务流程

用户成功登录账号；

在我的页面选择修改密码进入修改密码页面；

##### 1.2.4.2 页面原型

![image](https://internal-api-drive-stream.feishu.cn/space/api/box/stream/download/authcode/?code=MTk1NTBhYzA3ODhiMDBlZTI4ZjAyNDIwMWFkNWIzODlfOWE3MzBiMGM2NjQ5M2QxNDZiYzJlMjI2Njk1ZjUzOGVfSUQ6NzUyMDQ4MjEzOTQ4MjYxOTkzMl8xNzUxODcwMDQxOjE3NTE5NTY0NDFfVjM)

##### 1.2.4.3 业务逻辑

原密码输入框：输入密码后显示密码明文查看按钮及清空按钮，鼠标按下明文查看按钮密码明文展示，鼠标松开后密文展示，点击清空按钮清空已输入密码；

新密码输入框：输入密码后显示密码明文查看按钮及清空按钮，鼠标按下明文查看按钮密码明文展示，鼠标松开后密文展示，点击清空按钮清空已输入密码；

确认密码：输入密码后显示密码明文查看按钮及清空按钮，鼠标按下明文查看按钮密码明文展示，鼠标松开后密文展示，点击清空按钮清空已输入密码；

验证码：点击【获取验证码】按钮向登录账号绑定手机号发送6位随机数字验证码，验证码已发送后【获取验证码】按钮展示60秒倒计时，倒计时结束后恢复原状，验证码有效期为60秒；

所有输入框获取焦点时提示文字消失且输入框边框变为绿色，失去焦点时恢复原状；

【取消】按钮：点击【取消】按钮取消修改密码，返回至我的页面；

【提交】按钮：点击【提交】按钮依次校验密码、验证码，若某一项校验出问题则在对应输入框下方红字提醒用户错误原因，全部校验通过则提示重置密码成功；


2025-07-07 14:34:00,121 - main - INFO - 开始调用图谱生成测试用例
2025-07-07 14:34:00,132 - langgraph_use2 - INFO - [Step 1] 尝试直接从 PRD 文本提取标题
2025-07-07 14:34:00,133 - langgraph_use2 - INFO - [Step 1] 提取标题成功: B端产品登录功能需求文档范文
2025-07-07 14:34:00,133 - langgraph_use2 - INFO - [Step 2] 提取测试点
2025-07-07 14:35:02,840 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-07 14:35:02,843 - langgraph_use2 - INFO - [Step 3] 优化测试点
2025-07-07 14:36:34,045 - uvicorn.error - INFO - Shutting down
2025-07-07 14:36:34,156 - uvicorn.error - INFO - Waiting for background tasks to complete. (CTRL+C to force quit)
2025-07-07 14:36:50,751 - langgraph_use2 - ERROR - [Step 3] 优化失败: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection.py", line 103, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http11.py", line 136, in handle_async_request
    raise exc
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http11.py", line 106, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http11.py", line 177, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http11.py", line 217, in _receive_event
    data = await self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_backends\anyio.py", line 32, in read
    with map_exceptions(exc_map):
  File "C:\Users\HUAWEI\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\pythonProject\generateTestCases\langgraph_use2.py", line 93, in optimize_requirements
    optimized = await call_model2(prompt)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\generateTestCases\model_api2.py", line 42, in call_model2
    response = await client.post(f"{ARK_BASE_URL}/chat/completions", json=payload, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_client.py", line 1859, in post
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 393, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\HUAWEI\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadError

2025-07-07 14:36:50,752 - main - ERROR - 生成测试用例失败
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection.py", line 103, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http11.py", line 136, in handle_async_request
    raise exc
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http11.py", line 106, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http11.py", line 177, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http11.py", line 217, in _receive_event
    data = await self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_backends\anyio.py", line 32, in read
    with map_exceptions(exc_map):
  File "C:\Users\HUAWEI\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\pythonProject\generateTestCases\main.py", line 153, in generate_testcases_api
    result_graph = await graph.ainvoke(initial_state)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\langgraph\pregel\__init__.py", line 2788, in ainvoke
    async for chunk in self.astream(
  File "D:\pythonProject\venv\Lib\site-packages\langgraph\pregel\__init__.py", line 2655, in astream
    async for _ in runner.atick(
  File "D:\pythonProject\venv\Lib\site-packages\langgraph\pregel\runner.py", line 295, in atick
    await arun_with_retry(
  File "D:\pythonProject\venv\Lib\site-packages\langgraph\pregel\retry.py", line 136, in arun_with_retry
    return await task.proc.ainvoke(task.input, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\langgraph\utils\runnable.py", line 672, in ainvoke
    input = await asyncio.create_task(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\langgraph\utils\runnable.py", line 440, in ainvoke
    ret = await self.afunc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\generateTestCases\langgraph_use2.py", line 93, in optimize_requirements
    optimized = await call_model2(prompt)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\generateTestCases\model_api2.py", line 42, in call_model2
    response = await client.post(f"{ARK_BASE_URL}/chat/completions", json=payload, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_client.py", line 1859, in post
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 393, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\HUAWEI\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadError
During task with name 'step3_optimize_requirements' and id '0631e004-e401-b5c4-2839-e1943073c86c'
2025-07-07 14:36:50,839 - uvicorn.error - INFO - Waiting for application shutdown.
2025-07-07 14:36:50,840 - uvicorn.error - INFO - Application shutdown complete.
2025-07-07 14:36:50,840 - uvicorn.error - INFO - Finished server process [10452]
