2025-07-08 22:00:26,385 - __main__ - INFO - ==================================================
2025-07-08 22:00:26,385 - __main__ - INFO - 应用程序启动 - 日志系统初始化完成
2025-07-08 22:00:26,385 - __main__ - INFO - 日志文件路径: D:\pythonProject\generateTestCases\logs\app_20250708_220026.log
2025-07-08 22:00:26,385 - __main__ - INFO - ==================================================
2025-07-08 22:00:26,387 - __main__ - INFO - 启动 frpc: D:\pythonProject\generateTestCases\frpc.exe -c D:\pythonProject\generateTestCases\frpc.toml
2025-07-08 22:00:26,430 - __main__ - INFO - frpc 启动成功
2025-07-08 22:00:26,472 - main - INFO - ==================================================
2025-07-08 22:00:26,472 - main - INFO - 应用程序启动 - 日志系统初始化完成
2025-07-08 22:00:26,472 - main - INFO - 日志文件路径: D:\pythonProject\generateTestCases\logs\app_20250708_220026.log
2025-07-08 22:00:26,472 - main - INFO - ==================================================
2025-07-08 22:00:26,474 - uvicorn.error - INFO - Started server process [20024]
2025-07-08 22:00:26,474 - uvicorn.error - INFO - Waiting for application startup.
2025-07-08 22:00:26,475 - uvicorn.error - INFO - Application startup complete.
2025-07-08 22:00:26,475 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
2025-07-08 22:00:45,826 - main - INFO - 收到飞书请求，document_id=KExEdM3URoe4JdxRyU6cduwHnZd
2025-07-08 22:00:46,293 - httpx - INFO - HTTP Request: GET https://open.feishu.cn/open-apis/docx/v1/documents/KExEdM3URoe4JdxRyU6cduwHnZd/blocks?limit=100 "HTTP/1.1 200 OK"
2025-07-08 22:00:46,815 - httpx - INFO - HTTP Request: GET https://open.feishu.cn/open-apis/drive/v1/medias/batch_get_tmp_download_url?file_tokens=SZPlbksxNo9q2AxkE3TcDp3gnlb "HTTP/1.1 200 OK"
2025-07-08 22:00:47,422 - httpx - INFO - HTTP Request: GET https://api3-eeft-drive.feishu.cn/space/api/box/stream/download/authcode/?code=ZDI4ZDRmNzZjNzJmODE5YmJkZGZkZTQ0Y2Y4MDVkNzFfMTU5YWM2ZWNhYjRhNWM4ZDliMjFkY2RiZTY2MjVjOTBfSUQ6NzUyMDQ4MjE0MTQwNzYwODgzNV8xNzUxOTgzMjQ3OjE3NTIwNjk2NDdfVjM "HTTP/1.1 200 OK"
2025-07-08 22:00:50,999 - httpx - INFO - HTTP Request: POST https://sm.ms/api/v2/upload "HTTP/1.1 200 OK"
2025-07-08 22:00:51,000 - feishu_api - WARNING - 图片 SZPlbksxNo9q2AxkE3TcDp3gnlb 上传图床失败：图床上传失败: You must be logged in to use.
2025-07-08 22:00:51,405 - httpx - INFO - HTTP Request: GET https://open.feishu.cn/open-apis/drive/v1/medias/batch_get_tmp_download_url?file_tokens=JqINbXfOlofwdHxsaYecenlsnAh "HTTP/1.1 200 OK"
2025-07-08 22:00:51,662 - httpx - INFO - HTTP Request: GET https://internal-api-drive-stream.feishu.cn/space/api/box/stream/download/authcode/?code=M2IwOTZjOGIyNzBlMGJiMTQ3NjMwMWExOWY5N2IyMWZfZWNkMmM1YTQ0OGFhYjk5YzU2OGRiZmM0MWU4NWQwNTRfSUQ6NzUyMTgwNjA4OTg5MDEwMzI5N18xNzUxOTgzMjUyOjE3NTIwNjk2NTJfVjM "HTTP/1.1 200 OK"
2025-07-08 22:00:53,946 - httpx - INFO - HTTP Request: POST https://sm.ms/api/v2/upload "HTTP/1.1 200 OK"
2025-07-08 22:00:53,947 - feishu_api - WARNING - 图片 JqINbXfOlofwdHxsaYecenlsnAh 上传图床失败：图床上传失败: You must be logged in to use.
2025-07-08 22:00:54,403 - httpx - INFO - HTTP Request: GET https://open.feishu.cn/open-apis/drive/v1/medias/batch_get_tmp_download_url?file_tokens=ZPq4buihSoeZrCxt6jQcMli8n2f "HTTP/1.1 200 OK"
2025-07-08 22:00:54,664 - httpx - INFO - HTTP Request: GET https://internal-api-drive-stream.feishu.cn/space/api/box/stream/download/authcode/?code=OGRjMTYyY2I0N2NhZDEzYTZlZmNjZjFlYTJjZjdlMzlfOWM5ZTA1NDdhYjBjNzBjZTJiYzI4NmZkMzM2MmE0NWRfSUQ6NzUyMDQ4MjE0MTE3MjQ5ODQzNV8xNzUxOTgzMjU1OjE3NTIwNjk2NTVfVjM "HTTP/1.1 200 OK"
2025-07-08 22:00:56,267 - httpx - INFO - HTTP Request: POST https://sm.ms/api/v2/upload "HTTP/1.1 200 OK"
2025-07-08 22:00:56,267 - feishu_api - WARNING - 图片 ZPq4buihSoeZrCxt6jQcMli8n2f 上传图床失败：图床上传失败: You must be logged in to use.
2025-07-08 22:00:56,662 - httpx - INFO - HTTP Request: GET https://open.feishu.cn/open-apis/drive/v1/medias/batch_get_tmp_download_url?file_tokens=I69ubTn76oLpwRxLIP6cjz0tnWb "HTTP/1.1 200 OK"
2025-07-08 22:00:57,117 - httpx - INFO - HTTP Request: GET https://internal-api-drive-stream.feishu.cn/space/api/box/stream/download/authcode/?code=OGI1NmI0ODA5MDY4MDIwOGVlZmNmNjliMjU3ZjhiYmRfNjRiY2Q5ZjAzZTVmNTkwMWU4ZGZjNGIwYTQ3NjNkMTRfSUQ6NzUyMDQ4MjE0MDI2MTgyNjU3OV8xNzUxOTgzMjU3OjE3NTIwNjk2NTdfVjM "HTTP/1.1 200 OK"
2025-07-08 22:00:58,480 - httpx - INFO - HTTP Request: POST https://sm.ms/api/v2/upload "HTTP/1.1 200 OK"
2025-07-08 22:00:58,488 - feishu_api - WARNING - 图片 I69ubTn76oLpwRxLIP6cjz0tnWb 上传图床失败：图床上传失败: You must be logged in to use.
2025-07-08 22:00:58,946 - httpx - INFO - HTTP Request: GET https://open.feishu.cn/open-apis/drive/v1/medias/batch_get_tmp_download_url?file_tokens=G7hCbfD1UoCXnwxK0hIcXbqhnPg "HTTP/1.1 200 OK"
2025-07-08 22:00:59,216 - httpx - INFO - HTTP Request: GET https://internal-api-drive-stream.feishu.cn/space/api/box/stream/download/authcode/?code=YmZjNzAxY2VmOWY2Yjk0NDJhOGYxMzAzNGY3YTE1MzdfOTM5OTVkYmQyNjFkMjcwMzUzOTA4YTJkYjBhOGM2ZjlfSUQ6NzUyMDQ4MjEzODAwMjA5NjE1Nl8xNzUxOTgzMjU5OjE3NTIwNjk2NTlfVjM "HTTP/1.1 200 OK"
2025-07-08 22:01:00,467 - httpx - INFO - HTTP Request: POST https://sm.ms/api/v2/upload "HTTP/1.1 200 OK"
2025-07-08 22:01:00,468 - feishu_api - WARNING - 图片 G7hCbfD1UoCXnwxK0hIcXbqhnPg 上传图床失败：图床上传失败: You must be logged in to use.
2025-07-08 22:01:00,898 - httpx - INFO - HTTP Request: GET https://open.feishu.cn/open-apis/drive/v1/medias/batch_get_tmp_download_url?file_tokens=M5XibpflfokO3Dx25UQcS4zgnVh "HTTP/1.1 200 OK"
2025-07-08 22:01:01,306 - httpx - INFO - HTTP Request: GET https://internal-api-drive-stream.feishu.cn/space/api/box/stream/download/authcode/?code=OTg2MDY1ZDRjYTdkY2NiODQ1YzUwY2E2Y2NjZGZkNWFfNjhmM2QyZjU3Y2VkODU3YWIyMjk3OTI5ZGY1OWU0NjFfSUQ6NzUyMDQ4MjEzOTQ4MjYxOTkzMl8xNzUxOTgzMjYxOjE3NTIwNjk2NjFfVjM "HTTP/1.1 200 OK"
2025-07-08 22:01:02,637 - httpx - INFO - HTTP Request: POST https://sm.ms/api/v2/upload "HTTP/1.1 200 OK"
2025-07-08 22:01:02,638 - feishu_api - WARNING - 图片 M5XibpflfokO3Dx25UQcS4zgnVh 上传图床失败：图床上传失败: You must be logged in to use.
2025-07-08 22:01:02,639 - main - INFO - 提取的 PRD 文本:
# B端产品登录功能需求文档范文

### 1.1 功能概述

#### 1.1.1 业务流程图

![image]()

#### 1.1.2 功能架构

![image]()

### 1.2 功能说明

#### 1.2.1 账号登录

##### 1.2.1.1 业务流程

用户打开登录网址进入登录页面；

输入登录账号、密码、验证码进行登录；

##### 1.2.1.2 页面原型

![image]()

##### 1.2.1.3 逻辑说明

账号输入框：输入账号后显示清空操作按钮，点击清空按钮清空已输入的账号；

密码输入框：输入密码后显示密码明文查看按钮及清空按钮，鼠标按下明文查看按钮密码明文展示，鼠标松开后密文展示，点击清空按钮清空已输入密码；

验证码：验证码为4位随机的大写英文字母，单击验证码展示区域刷新验证码，验证码有效期为60秒；

所有输入框获取焦点时提示文字消失且边框变为绿色，失去焦点时恢复原状；

【登录】按钮：点击【登录】按钮时依次校验登录账号、密码、验证码，若某一项校验出问题则在对应输入框下方红字提醒用户错误原因，全部校验通过则成功登录并进入系统首页；

【找回密码】按钮：点击【找回密码】按钮跳转至找回密码页面；

账号首次成功登录时弹窗提示账号首次登录时需修改初始密码，点击【确定】按钮跳转至修改初始密码页面，初始密码修改后需要重新输入账号、密码、验证码进行登录；

#### 1.2.2 重置初始密码

##### 1.2.2.1 业务流程

用户初次成功登录账号后弹窗提示用户修改初始密码；

点击弹窗的【确定】按钮后页面跳转至重置初始密码页面；

##### 1.2.2.2 页面原型

![image]()

##### 1.2.2.3 业务逻辑

新密码输入框：输入密码后显示密码明文查看按钮及清空按钮，鼠标按下明文查看按钮密码明文展示，鼠标松开后密文展示，点击清空按钮清空已输入密码；

确认密码：输入密码后显示密码明文查看按钮及清空按钮，鼠标按下明文查看按钮密码明文展示，鼠标松开后密文展示，点击清空按钮清空已输入密码；

验证码：点击【获取验证码】按钮向登录账号绑定手机号发送6位随机数字验证码，验证码已发送后【获取验证码】按钮展示60秒倒计时，倒计时结束后恢复原状，验证码有效期为60秒；

所有输入框获取焦点时提示文字消失且输入框边框变为绿色，失去焦点时恢复原状；

【取消】按钮：点击【取消】按钮取消修改初始密码，返回至登录页面；

【提交】按钮：点击【提交】按钮依次校验密码、验证码，若某一项校验出问题则在对应输入框下方红字提醒用户错误原因，全部校验通过则提示重置密码成功，然后返回至登录页面；

#### 1.2.3 找回密码

##### 1.2.3.1 业务流程

用户打开登录网址进入登录页面；

忘记登录密码后在登录页面页面点击【找回密码】按钮进入找回密码页面；

##### 1.2.3.2 页面原型

![image]()

##### 1.2.3.3 业务逻辑

新密码输入框：输入密码后显示密码明文查看按钮及清空按钮，鼠标按下明文查看按钮密码明文展示，鼠标松开后密文展示，点击清空按钮清空已输入密码；

确认密码：输入密码后显示密码明文查看按钮及清空按钮，鼠标按下明文查看按钮密码明文展示，鼠标松开后密文展示，点击清空按钮清空已输入密码；

验证码：点击【获取验证码】按钮向登录账号绑定手机号发送6位随机数字验证码，验证码已发送后【获取验证码】按钮展示60秒倒计时，倒计时结束后恢复原状，验证码有效期为60秒；

所有输入框获取焦点时提示文字消失且输入框边框变为绿色，失去焦点时恢复原状；

【取消】按钮：点击【取消】按钮取消修改初始密码，返回至登录页面；

【提交】按钮：点击【提交】按钮依次校验密码、验证码，若某一项校验出问题则在对应输入框下方红字提醒用户错误原因，全部校验通过则提示重置密码成功，然后返回至登录页面；

#### 1.2.4 修改密码

##### 1.2.4.1 业务流程

用户成功登录账号；

在我的页面选择修改密码进入修改密码页面；

##### 1.2.4.2 页面原型

![image]()

##### 1.2.4.3 业务逻辑

原密码输入框：输入密码后显示密码明文查看按钮及清空按钮，鼠标按下明文查看按钮密码明文展示，鼠标松开后密文展示，点击清空按钮清空已输入密码；

新密码输入框：输入密码后显示密码明文查看按钮及清空按钮，鼠标按下明文查看按钮密码明文展示，鼠标松开后密文展示，点击清空按钮清空已输入密码；

确认密码：输入密码后显示密码明文查看按钮及清空按钮，鼠标按下明文查看按钮密码明文展示，鼠标松开后密文展示，点击清空按钮清空已输入密码；

验证码：点击【获取验证码】按钮向登录账号绑定手机号发送6位随机数字验证码，验证码已发送后【获取验证码】按钮展示60秒倒计时，倒计时结束后恢复原状，验证码有效期为60秒；

所有输入框获取焦点时提示文字消失且输入框边框变为绿色，失去焦点时恢复原状；

【取消】按钮：点击【取消】按钮取消修改密码，返回至我的页面；

【提交】按钮：点击【提交】按钮依次校验密码、验证码，若某一项校验出问题则在对应输入框下方红字提醒用户错误原因，全部校验通过则提示重置密码成功；


2025-07-08 22:01:02,642 - main - INFO - 开始调用图谱生成测试用例
2025-07-08 22:01:02,659 - langgraph_use2 - INFO - [Step 1] 尝试直接从 PRD 文本提取标题
2025-07-08 22:01:02,659 - langgraph_use2 - INFO - [Step 1] 提取标题成功: B端产品登录功能需求文档范文
2025-07-08 22:01:02,660 - langgraph_use2 - INFO - [Step 2] 提取测试点
2025-07-08 22:01:06,706 - uvicorn.error - INFO - Shutting down
2025-07-08 22:01:06,815 - uvicorn.error - INFO - Waiting for background tasks to complete. (CTRL+C to force quit)
2025-07-08 22:01:58,243 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:01:58,245 - langgraph_use2 - INFO - [Step 3] 优化测试点
2025-07-08 22:03:25,766 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:25,891 - langgraph_use2 - INFO - [Step 4] 生成测试用例
2025-07-08 22:03:25,892 - langgraph_use2 - INFO - 生成第 1 个用例，第 1 次尝试
2025-07-08 22:03:25,917 - langgraph_use2 - INFO - 生成第 2 个用例，第 1 次尝试
2025-07-08 22:03:25,946 - langgraph_use2 - INFO - 生成第 3 个用例，第 1 次尝试
2025-07-08 22:03:25,975 - langgraph_use2 - INFO - 生成第 4 个用例，第 1 次尝试
2025-07-08 22:03:25,999 - langgraph_use2 - INFO - 生成第 5 个用例，第 1 次尝试
2025-07-08 22:03:26,029 - langgraph_use2 - INFO - 生成第 6 个用例，第 1 次尝试
2025-07-08 22:03:26,054 - langgraph_use2 - INFO - 生成第 7 个用例，第 1 次尝试
2025-07-08 22:03:26,081 - langgraph_use2 - INFO - 生成第 8 个用例，第 1 次尝试
2025-07-08 22:03:26,106 - langgraph_use2 - INFO - 生成第 9 个用例，第 1 次尝试
2025-07-08 22:03:26,132 - langgraph_use2 - INFO - 生成第 10 个用例，第 1 次尝试
2025-07-08 22:03:26,159 - langgraph_use2 - INFO - 生成第 11 个用例，第 1 次尝试
2025-07-08 22:03:26,184 - langgraph_use2 - INFO - 生成第 12 个用例，第 1 次尝试
2025-07-08 22:03:26,211 - langgraph_use2 - INFO - 生成第 13 个用例，第 1 次尝试
2025-07-08 22:03:26,237 - langgraph_use2 - INFO - 生成第 14 个用例，第 1 次尝试
2025-07-08 22:03:26,261 - langgraph_use2 - INFO - 生成第 15 个用例，第 1 次尝试
2025-07-08 22:03:26,289 - langgraph_use2 - INFO - 生成第 16 个用例，第 1 次尝试
2025-07-08 22:03:26,315 - langgraph_use2 - INFO - 生成第 17 个用例，第 1 次尝试
2025-07-08 22:03:26,345 - langgraph_use2 - INFO - 生成第 18 个用例，第 1 次尝试
2025-07-08 22:03:26,372 - langgraph_use2 - INFO - 生成第 19 个用例，第 1 次尝试
2025-07-08 22:03:26,400 - langgraph_use2 - INFO - 生成第 20 个用例，第 1 次尝试
2025-07-08 22:03:26,430 - langgraph_use2 - INFO - 生成第 21 个用例，第 1 次尝试
2025-07-08 22:03:26,454 - langgraph_use2 - INFO - 生成第 22 个用例，第 1 次尝试
2025-07-08 22:03:26,481 - langgraph_use2 - INFO - 生成第 23 个用例，第 1 次尝试
2025-07-08 22:03:26,514 - langgraph_use2 - INFO - 生成第 24 个用例，第 1 次尝试
2025-07-08 22:03:26,540 - langgraph_use2 - INFO - 生成第 25 个用例，第 1 次尝试
2025-07-08 22:03:26,567 - langgraph_use2 - INFO - 生成第 26 个用例，第 1 次尝试
2025-07-08 22:03:26,595 - langgraph_use2 - INFO - 生成第 27 个用例，第 1 次尝试
2025-07-08 22:03:26,626 - langgraph_use2 - INFO - 生成第 28 个用例，第 1 次尝试
2025-07-08 22:03:26,650 - langgraph_use2 - INFO - 生成第 29 个用例，第 1 次尝试
2025-07-08 22:03:26,682 - langgraph_use2 - INFO - 生成第 30 个用例，第 1 次尝试
2025-07-08 22:03:30,821 - langgraph_use2 - WARNING - 第 9 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProje
2025-07-08 22:03:30,822 - langgraph_use2 - INFO - 生成第 31 个用例，第 1 次尝试
2025-07-08 22:03:30,847 - langgraph_use2 - WARNING - 第 1 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProje
2025-07-08 22:03:30,848 - langgraph_use2 - INFO - 生成第 32 个用例，第 1 次尝试
2025-07-08 22:03:30,890 - langgraph_use2 - WARNING - 第 2 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProje
2025-07-08 22:03:30,892 - langgraph_use2 - WARNING - 第 19 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:30,894 - langgraph_use2 - WARNING - 第 7 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProje
2025-07-08 22:03:30,896 - langgraph_use2 - WARNING - 第 24 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:30,898 - langgraph_use2 - WARNING - 第 30 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:30,900 - langgraph_use2 - WARNING - 第 17 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:30,902 - langgraph_use2 - WARNING - 第 4 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProje
2025-07-08 22:03:30,903 - langgraph_use2 - WARNING - 第 22 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:30,905 - langgraph_use2 - WARNING - 第 29 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:30,907 - langgraph_use2 - WARNING - 第 23 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:30,909 - langgraph_use2 - WARNING - 第 3 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProje
2025-07-08 22:03:30,912 - langgraph_use2 - WARNING - 第 25 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:30,914 - langgraph_use2 - WARNING - 第 28 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:30,916 - langgraph_use2 - WARNING - 第 11 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:30,918 - langgraph_use2 - WARNING - 第 15 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:30,920 - langgraph_use2 - WARNING - 第 16 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:30,922 - langgraph_use2 - WARNING - 第 20 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:30,924 - langgraph_use2 - WARNING - 第 18 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:30,926 - langgraph_use2 - WARNING - 第 27 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:30,926 - langgraph_use2 - INFO - 生成第 33 个用例，第 1 次尝试
2025-07-08 22:03:30,956 - langgraph_use2 - INFO - 生成第 34 个用例，第 1 次尝试
2025-07-08 22:03:30,982 - langgraph_use2 - INFO - 生成第 35 个用例，第 1 次尝试
2025-07-08 22:03:31,014 - langgraph_use2 - INFO - 生成第 36 个用例，第 1 次尝试
2025-07-08 22:03:31,043 - langgraph_use2 - INFO - 生成第 37 个用例，第 1 次尝试
2025-07-08 22:03:31,072 - langgraph_use2 - INFO - 生成第 38 个用例，第 1 次尝试
2025-07-08 22:03:31,109 - langgraph_use2 - INFO - 生成第 39 个用例，第 1 次尝试
2025-07-08 22:03:31,136 - langgraph_use2 - INFO - 生成第 40 个用例，第 1 次尝试
2025-07-08 22:03:31,165 - langgraph_use2 - INFO - 生成第 41 个用例，第 1 次尝试
2025-07-08 22:03:31,190 - langgraph_use2 - INFO - 生成第 42 个用例，第 1 次尝试
2025-07-08 22:03:31,220 - langgraph_use2 - INFO - 生成第 43 个用例，第 1 次尝试
2025-07-08 22:03:31,251 - langgraph_use2 - INFO - 生成第 44 个用例，第 1 次尝试
2025-07-08 22:03:31,280 - langgraph_use2 - INFO - 生成第 45 个用例，第 1 次尝试
2025-07-08 22:03:31,306 - langgraph_use2 - INFO - 生成第 46 个用例，第 1 次尝试
2025-07-08 22:03:31,339 - langgraph_use2 - INFO - 生成第 47 个用例，第 1 次尝试
2025-07-08 22:03:31,377 - langgraph_use2 - INFO - 生成第 48 个用例，第 1 次尝试
2025-07-08 22:03:31,415 - langgraph_use2 - INFO - 生成第 49 个用例，第 1 次尝试
2025-07-08 22:03:31,450 - langgraph_use2 - INFO - 生成第 50 个用例，第 1 次尝试
2025-07-08 22:03:31,488 - langgraph_use2 - INFO - 生成第 51 个用例，第 1 次尝试
2025-07-08 22:03:35,618 - langgraph_use2 - WARNING - 第 38 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:35,621 - langgraph_use2 - WARNING - 第 39 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:35,621 - langgraph_use2 - INFO - 生成第 52 个用例，第 1 次尝试
2025-07-08 22:03:35,646 - langgraph_use2 - INFO - 生成第 53 个用例，第 1 次尝试
2025-07-08 22:03:35,675 - langgraph_use2 - WARNING - 第 48 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:35,677 - langgraph_use2 - WARNING - 第 36 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:35,679 - langgraph_use2 - WARNING - 第 45 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:35,680 - langgraph_use2 - WARNING - 第 49 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:35,683 - langgraph_use2 - WARNING - 第 43 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:35,685 - langgraph_use2 - WARNING - 第 32 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:35,687 - langgraph_use2 - WARNING - 第 51 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:35,690 - langgraph_use2 - WARNING - 第 34 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:35,691 - langgraph_use2 - WARNING - 第 47 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:35,693 - langgraph_use2 - WARNING - 第 37 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:35,693 - langgraph_use2 - INFO - 生成第 54 个用例，第 1 次尝试
2025-07-08 22:03:35,718 - langgraph_use2 - INFO - 生成第 55 个用例，第 1 次尝试
2025-07-08 22:03:35,743 - langgraph_use2 - INFO - 生成第 56 个用例，第 1 次尝试
2025-07-08 22:03:35,768 - langgraph_use2 - INFO - 生成第 57 个用例，第 1 次尝试
2025-07-08 22:03:35,790 - langgraph_use2 - INFO - 生成第 58 个用例，第 1 次尝试
2025-07-08 22:03:35,815 - langgraph_use2 - INFO - 生成第 59 个用例，第 1 次尝试
2025-07-08 22:03:35,840 - langgraph_use2 - INFO - 生成第 60 个用例，第 1 次尝试
2025-07-08 22:03:35,863 - langgraph_use2 - INFO - 生成第 61 个用例，第 1 次尝试
2025-07-08 22:03:35,890 - langgraph_use2 - INFO - 生成第 62 个用例，第 1 次尝试
2025-07-08 22:03:35,915 - langgraph_use2 - INFO - 生成第 63 个用例，第 1 次尝试
2025-07-08 22:03:36,620 - langgraph_use2 - WARNING - 第 40 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:36,620 - langgraph_use2 - INFO - 生成第 64 个用例，第 1 次尝试
2025-07-08 22:03:36,647 - langgraph_use2 - WARNING - 第 44 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:36,648 - langgraph_use2 - INFO - 生成第 65 个用例，第 1 次尝试
2025-07-08 22:03:36,672 - langgraph_use2 - WARNING - 第 50 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:36,673 - langgraph_use2 - INFO - 生成第 66 个用例，第 1 次尝试
2025-07-08 22:03:40,044 - langgraph_use2 - WARNING - 第 59 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:40,044 - langgraph_use2 - INFO - 生成第 67 个用例，第 1 次尝试
2025-07-08 22:03:40,071 - langgraph_use2 - WARNING - 第 56 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:40,072 - langgraph_use2 - INFO - 生成第 68 个用例，第 1 次尝试
2025-07-08 22:03:40,098 - langgraph_use2 - WARNING - 第 60 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:40,098 - langgraph_use2 - INFO - 生成第 69 个用例，第 1 次尝试
2025-07-08 22:03:41,060 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:41,061 - langgraph_use2 - INFO -  第 5 个用例生成成功，用时 15.06s
2025-07-08 22:03:41,062 - langgraph_use2 - INFO - 生成第 70 个用例，第 1 次尝试
2025-07-08 22:03:41,780 - langgraph_use2 - WARNING - 第 64 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:41,781 - langgraph_use2 - INFO - 生成第 71 个用例，第 1 次尝试
2025-07-08 22:03:43,257 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:43,260 - langgraph_use2 - INFO -  第 26 个用例生成成功，用时 16.69s
2025-07-08 22:03:43,261 - langgraph_use2 - INFO - 生成第 72 个用例，第 1 次尝试
2025-07-08 22:03:43,892 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:43,895 - langgraph_use2 - INFO -  第 8 个用例生成成功，用时 17.81s
2025-07-08 22:03:43,895 - langgraph_use2 - INFO - 生成第 73 个用例，第 1 次尝试
2025-07-08 22:03:44,144 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:44,146 - langgraph_use2 - INFO -  第 12 个用例生成成功，用时 17.96s
2025-07-08 22:03:44,146 - langgraph_use2 - INFO - 生成第 74 个用例，第 1 次尝试
2025-07-08 22:03:44,215 - langgraph_use2 - WARNING - 第 69 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:44,217 - langgraph_use2 - WARNING - 第 68 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:44,217 - langgraph_use2 - INFO - 生成第 75 个用例，第 1 次尝试
2025-07-08 22:03:44,244 - langgraph_use2 - INFO - 生成第 76 个用例，第 1 次尝试
2025-07-08 22:03:44,277 - langgraph_use2 - WARNING - 第 67 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:44,278 - langgraph_use2 - INFO - 生成第 77 个用例，第 1 次尝试
2025-07-08 22:03:45,342 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:45,345 - langgraph_use2 - INFO -  第 14 个用例生成成功，用时 19.11s
2025-07-08 22:03:45,345 - langgraph_use2 - INFO - 生成第 78 个用例，第 1 次尝试
2025-07-08 22:03:45,745 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:45,748 - langgraph_use2 - INFO -  第 10 个用例生成成功，用时 19.62s
2025-07-08 22:03:45,748 - langgraph_use2 - INFO - 生成第 79 个用例，第 1 次尝试
2025-07-08 22:03:45,911 - langgraph_use2 - WARNING - 第 71 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:45,911 - langgraph_use2 - INFO - 生成第 80 个用例，第 1 次尝试
2025-07-08 22:03:46,695 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:46,697 - langgraph_use2 - INFO -  第 13 个用例生成成功，用时 20.49s
2025-07-08 22:03:46,697 - langgraph_use2 - INFO - 生成第 81 个用例，第 1 次尝试
2025-07-08 22:03:47,379 - langgraph_use2 - WARNING - 第 72 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:47,380 - langgraph_use2 - INFO - 生成第 82 个用例，第 1 次尝试
2025-07-08 22:03:47,487 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:47,490 - langgraph_use2 - INFO -  第 21 个用例生成成功，用时 21.06s
2025-07-08 22:03:47,490 - langgraph_use2 - INFO - 生成第 83 个用例，第 1 次尝试
2025-07-08 22:03:47,624 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:47,628 - langgraph_use2 - INFO -  第 31 个用例生成成功，用时 16.81s
2025-07-08 22:03:47,628 - langgraph_use2 - INFO - 生成第 84 个用例，第 1 次尝试
2025-07-08 22:03:48,026 - langgraph_use2 - WARNING - 第 73 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:48,026 - langgraph_use2 - INFO - 生成第 85 个用例，第 1 次尝试
2025-07-08 22:03:48,234 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:48,236 - langgraph_use2 - INFO -  第 6 个用例生成成功，用时 22.21s
2025-07-08 22:03:48,236 - langgraph_use2 - INFO - 生成第 86 个用例，第 1 次尝试
2025-07-08 22:03:48,399 - langgraph_use2 - WARNING - 第 77 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:48,400 - langgraph_use2 - WARNING - 第 76 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:48,400 - langgraph_use2 - INFO - 生成第 87 个用例，第 1 次尝试
2025-07-08 22:03:48,428 - langgraph_use2 - INFO - 生成第 88 个用例，第 1 次尝试
2025-07-08 22:03:50,378 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:50,380 - langgraph_use2 - INFO -  第 62 个用例生成成功，用时 14.49s
2025-07-08 22:03:50,381 - langgraph_use2 - INFO - 生成第 89 个用例，第 1 次尝试
2025-07-08 22:03:51,172 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:51,175 - langgraph_use2 - INFO -  第 58 个用例生成成功，用时 15.38s
2025-07-08 22:03:51,176 - langgraph_use2 - INFO - 生成第 90 个用例，第 1 次尝试
2025-07-08 22:03:51,290 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:51,293 - langgraph_use2 - INFO -  第 41 个用例生成成功，用时 20.13s
2025-07-08 22:03:51,293 - langgraph_use2 - INFO - 生成第 91 个用例，第 1 次尝试
2025-07-08 22:03:51,366 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:51,368 - langgraph_use2 - INFO -  第 57 个用例生成成功，用时 15.60s
2025-07-08 22:03:51,368 - langgraph_use2 - INFO - 生成第 9 个用例，第 2 次尝试
2025-07-08 22:03:51,508 - langgraph_use2 - WARNING - 第 82 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:51,508 - langgraph_use2 - INFO - 生成第 1 个用例，第 2 次尝试
2025-07-08 22:03:51,623 - langgraph_use2 - WARNING - 第 83 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:51,624 - langgraph_use2 - INFO - 生成第 19 个用例，第 2 次尝试
2025-07-08 22:03:51,859 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:51,863 - langgraph_use2 - INFO -  第 46 个用例生成成功，用时 20.56s
2025-07-08 22:03:51,863 - langgraph_use2 - INFO - 生成第 22 个用例，第 2 次尝试
2025-07-08 22:03:52,144 - langgraph_use2 - WARNING - 第 85 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:52,144 - langgraph_use2 - INFO - 生成第 30 个用例，第 2 次尝试
2025-07-08 22:03:52,182 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:52,187 - langgraph_use2 - INFO -  第 42 个用例生成成功，用时 21.00s
2025-07-08 22:03:52,187 - langgraph_use2 - INFO - 生成第 7 个用例，第 2 次尝试
2025-07-08 22:03:52,732 - langgraph_use2 - WARNING - 第 84 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:52,732 - langgraph_use2 - INFO - 生成第 4 个用例，第 2 次尝试
2025-07-08 22:03:53,519 - langgraph_use2 - WARNING - 第 88 个测试点失败（第 1 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:53,519 - langgraph_use2 - INFO - 生成第 2 个用例，第 2 次尝试
2025-07-08 22:03:53,628 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:53,633 - langgraph_use2 - INFO -  第 54 个用例生成成功，用时 17.94s
2025-07-08 22:03:53,633 - langgraph_use2 - INFO - 生成第 17 个用例，第 2 次尝试
2025-07-08 22:03:53,696 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:53,701 - langgraph_use2 - INFO -  第 53 个用例生成成功，用时 18.05s
2025-07-08 22:03:53,701 - langgraph_use2 - INFO - 生成第 24 个用例，第 2 次尝试
2025-07-08 22:03:53,802 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:53,804 - langgraph_use2 - INFO -  第 63 个用例生成成功，用时 17.89s
2025-07-08 22:03:53,805 - langgraph_use2 - INFO - 生成第 16 个用例，第 2 次尝试
2025-07-08 22:03:53,833 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:53,837 - langgraph_use2 - INFO -  第 33 个用例生成成功，用时 22.91s
2025-07-08 22:03:53,838 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:53,838 - langgraph_use2 - INFO - 生成第 3 个用例，第 2 次尝试
2025-07-08 22:03:53,872 - langgraph_use2 - INFO -  第 52 个用例生成成功，用时 18.25s
2025-07-08 22:03:53,873 - langgraph_use2 - INFO - 生成第 25 个用例，第 2 次尝试
2025-07-08 22:03:53,906 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:53,910 - langgraph_use2 - INFO -  第 65 个用例生成成功，用时 17.26s
2025-07-08 22:03:53,911 - langgraph_use2 - INFO - 生成第 15 个用例，第 2 次尝试
2025-07-08 22:03:54,556 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:54,562 - langgraph_use2 - INFO -  第 61 个用例生成成功，用时 18.70s
2025-07-08 22:03:54,562 - langgraph_use2 - INFO - 生成第 29 个用例，第 2 次尝试
2025-07-08 22:03:55,632 - langgraph_use2 - WARNING - 第 1 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProje
2025-07-08 22:03:55,633 - langgraph_use2 - INFO - 生成第 23 个用例，第 2 次尝试
2025-07-08 22:03:55,685 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:55,690 - langgraph_use2 - INFO -  第 35 个用例生成成功，用时 24.71s
2025-07-08 22:03:55,690 - langgraph_use2 - INFO - 生成第 28 个用例，第 2 次尝试
2025-07-08 22:03:55,766 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:55,768 - langgraph_use2 - INFO -  第 55 个用例生成成功，用时 20.05s
2025-07-08 22:03:55,769 - langgraph_use2 - INFO - 生成第 11 个用例，第 2 次尝试
2025-07-08 22:03:56,859 - langgraph_use2 - WARNING - 第 4 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProje
2025-07-08 22:03:56,859 - langgraph_use2 - INFO - 生成第 18 个用例，第 2 次尝试
2025-07-08 22:03:57,631 - langgraph_use2 - WARNING - 第 2 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProje
2025-07-08 22:03:57,632 - langgraph_use2 - INFO - 生成第 27 个用例，第 2 次尝试
2025-07-08 22:03:58,022 - langgraph_use2 - WARNING - 第 16 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:58,022 - langgraph_use2 - INFO - 生成第 20 个用例，第 2 次尝试
2025-07-08 22:03:58,984 - langgraph_use2 - WARNING - 第 25 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:58,984 - langgraph_use2 - INFO - 生成第 38 个用例，第 2 次尝试
2025-07-08 22:03:59,128 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:03:59,130 - langgraph_use2 - INFO -  第 66 个用例生成成功，用时 22.46s
2025-07-08 22:03:59,130 - langgraph_use2 - INFO - 生成第 39 个用例，第 2 次尝试
2025-07-08 22:03:59,760 - langgraph_use2 - WARNING - 第 23 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:03:59,760 - langgraph_use2 - INFO - 生成第 36 个用例，第 2 次尝试
2025-07-08 22:04:00,783 - langgraph_use2 - WARNING - 第 28 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:00,783 - langgraph_use2 - INFO - 生成第 48 个用例，第 2 次尝试
2025-07-08 22:04:01,029 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:01,037 - langgraph_use2 - INFO -  第 70 个用例生成成功，用时 19.97s
2025-07-08 22:04:01,037 - langgraph_use2 - INFO - 生成第 32 个用例，第 2 次尝试
2025-07-08 22:04:01,752 - langgraph_use2 - WARNING - 第 27 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:01,752 - langgraph_use2 - INFO - 生成第 49 个用例，第 2 次尝试
2025-07-08 22:04:04,749 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:04,753 - langgraph_use2 - INFO -  第 78 个用例生成成功，用时 19.41s
2025-07-08 22:04:04,753 - langgraph_use2 - INFO - 生成第 45 个用例，第 2 次尝试
2025-07-08 22:04:05,263 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:05,267 - langgraph_use2 - INFO -  第 80 个用例生成成功，用时 19.36s
2025-07-08 22:04:05,267 - langgraph_use2 - INFO - 生成第 43 个用例，第 2 次尝试
2025-07-08 22:04:05,867 - langgraph_use2 - WARNING - 第 48 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:05,868 - langgraph_use2 - INFO - 生成第 51 个用例，第 2 次尝试
2025-07-08 22:04:05,902 - langgraph_use2 - WARNING - 第 49 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:05,902 - langgraph_use2 - INFO - 生成第 34 个用例，第 2 次尝试
2025-07-08 22:04:06,188 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:06,191 - langgraph_use2 - INFO -  第 75 个用例生成成功，用时 21.97s
2025-07-08 22:04:06,191 - langgraph_use2 - INFO - 生成第 37 个用例，第 2 次尝试
2025-07-08 22:04:07,193 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:07,196 - langgraph_use2 - INFO -  第 74 个用例生成成功，用时 23.05s
2025-07-08 22:04:07,197 - langgraph_use2 - INFO - 生成第 47 个用例，第 2 次尝试
2025-07-08 22:04:07,284 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:07,292 - langgraph_use2 - INFO -  第 91 个用例生成成功，用时 16.00s
2025-07-08 22:04:07,292 - langgraph_use2 - INFO - 生成第 40 个用例，第 2 次尝试
2025-07-08 22:04:07,340 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:07,346 - langgraph_use2 - INFO -  第 22 个用例生成成功，用时 15.48s
2025-07-08 22:04:07,347 - langgraph_use2 - INFO - 生成第 44 个用例，第 2 次尝试
2025-07-08 22:04:07,878 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:07,881 - langgraph_use2 - INFO -  第 15 个用例生成成功，用时 13.97s
2025-07-08 22:04:07,882 - langgraph_use2 - INFO - 生成第 50 个用例，第 2 次尝试
2025-07-08 22:04:09,269 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:09,271 - langgraph_use2 - INFO -  第 90 个用例生成成功，用时 18.10s
2025-07-08 22:04:09,271 - langgraph_use2 - INFO - 生成第 59 个用例，第 2 次尝试
2025-07-08 22:04:09,304 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:09,307 - langgraph_use2 - INFO -  第 24 个用例生成成功，用时 15.61s
2025-07-08 22:04:09,307 - langgraph_use2 - INFO - 生成第 56 个用例，第 2 次尝试
2025-07-08 22:04:09,365 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:09,368 - langgraph_use2 - INFO -  第 7 个用例生成成功，用时 17.18s
2025-07-08 22:04:09,368 - langgraph_use2 - INFO - 生成第 60 个用例，第 2 次尝试
2025-07-08 22:04:09,395 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:09,396 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:09,398 - langgraph_use2 - INFO -  第 87 个用例生成成功，用时 21.00s
2025-07-08 22:04:09,400 - langgraph_use2 - INFO -  第 19 个用例生成成功，用时 17.78s
2025-07-08 22:04:09,401 - langgraph_use2 - INFO - 生成第 64 个用例，第 2 次尝试
2025-07-08 22:04:09,427 - langgraph_use2 - INFO - 生成第 68 个用例，第 2 次尝试
2025-07-08 22:04:09,476 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:09,478 - langgraph_use2 - INFO -  第 3 个用例生成成功，用时 15.64s
2025-07-08 22:04:09,478 - langgraph_use2 - INFO - 生成第 69 个用例，第 2 次尝试
2025-07-08 22:04:09,608 - langgraph_use2 - WARNING - 第 36 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:09,608 - langgraph_use2 - INFO - 生成第 67 个用例，第 2 次尝试
2025-07-08 22:04:10,357 - langgraph_use2 - WARNING - 第 43 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:10,357 - langgraph_use2 - INFO - 生成第 71 个用例，第 2 次尝试
2025-07-08 22:04:10,837 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:10,840 - langgraph_use2 - INFO -  第 9 个用例生成成功，用时 19.47s
2025-07-08 22:04:10,840 - langgraph_use2 - INFO - 生成第 72 个用例，第 2 次尝试
2025-07-08 22:04:12,014 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:12,018 - langgraph_use2 - INFO -  第 79 个用例生成成功，用时 26.27s
2025-07-08 22:04:12,018 - langgraph_use2 - INFO - 生成第 73 个用例，第 2 次尝试
2025-07-08 22:04:12,407 - langgraph_use2 - WARNING - 第 47 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:12,407 - langgraph_use2 - INFO - 生成第 77 个用例，第 2 次尝试
2025-07-08 22:04:12,973 - langgraph_use2 - WARNING - 第 50 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:12,973 - langgraph_use2 - INFO - 生成第 76 个用例，第 2 次尝试
2025-07-08 22:04:13,486 - langgraph_use2 - WARNING - 第 56 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:13,486 - langgraph_use2 - INFO - 生成第 82 个用例，第 2 次尝试
2025-07-08 22:04:13,513 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:13,515 - langgraph_use2 - INFO -  第 11 个用例生成成功，用时 17.75s
2025-07-08 22:04:13,515 - langgraph_use2 - INFO - 生成第 83 个用例，第 2 次尝试
2025-07-08 22:04:13,543 - langgraph_use2 - WARNING - 第 60 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:13,544 - langgraph_use2 - INFO - 生成第 85 个用例，第 2 次尝试
2025-07-08 22:04:13,729 - langgraph_use2 - WARNING - 第 67 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:13,729 - langgraph_use2 - INFO - 生成第 84 个用例，第 2 次尝试
2025-07-08 22:04:14,449 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:14,453 - langgraph_use2 - INFO -  第 30 个用例生成成功，用时 22.31s
2025-07-08 22:04:14,453 - langgraph_use2 - INFO - 生成第 88 个用例，第 2 次尝试
2025-07-08 22:04:14,522 - langgraph_use2 - WARNING - 第 71 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:14,524 - langgraph_use2 - WARNING - 第 64 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:14,525 - langgraph_use2 - INFO - 生成第 1 个用例，第 3 次尝试
2025-07-08 22:04:14,579 - langgraph_use2 - INFO - 生成第 4 个用例，第 3 次尝试
2025-07-08 22:04:14,642 - langgraph_use2 - WARNING - 第 69 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:14,643 - langgraph_use2 - INFO - 生成第 2 个用例，第 3 次尝试
2025-07-08 22:04:14,727 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:14,732 - langgraph_use2 - INFO -  第 17 个用例生成成功，用时 21.10s
2025-07-08 22:04:14,733 - langgraph_use2 - INFO - 生成第 16 个用例，第 3 次尝试
2025-07-08 22:04:14,932 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:14,937 - langgraph_use2 - INFO -  第 29 个用例生成成功，用时 20.38s
2025-07-08 22:04:14,937 - langgraph_use2 - INFO - 生成第 25 个用例，第 3 次尝试
2025-07-08 22:04:15,091 - langgraph_use2 - WARNING - 第 72 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:15,092 - langgraph_use2 - INFO - 生成第 23 个用例，第 3 次尝试
2025-07-08 22:04:16,145 - langgraph_use2 - WARNING - 第 73 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:16,145 - langgraph_use2 - INFO - 生成第 28 个用例，第 3 次尝试
2025-07-08 22:04:16,173 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:16,176 - langgraph_use2 - INFO -  第 89 个用例生成成功，用时 25.79s
2025-07-08 22:04:16,176 - langgraph_use2 - INFO - 生成第 27 个用例，第 3 次尝试
2025-07-08 22:04:17,116 - langgraph_use2 - WARNING - 第 76 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:17,117 - langgraph_use2 - INFO - 生成第 48 个用例，第 3 次尝试
2025-07-08 22:04:17,467 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:17,471 - langgraph_use2 - INFO -  第 86 个用例生成成功，用时 29.24s
2025-07-08 22:04:17,472 - langgraph_use2 - INFO - 生成第 49 个用例，第 3 次尝试
2025-07-08 22:04:17,520 - langgraph_use2 - WARNING - 第 77 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:17,520 - langgraph_use2 - INFO - 生成第 36 个用例，第 3 次尝试
2025-07-08 22:04:17,570 - langgraph_use2 - WARNING - 第 34 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:17,571 - langgraph_use2 - INFO - 生成第 43 个用例，第 3 次尝试
2025-07-08 22:04:17,650 - langgraph_use2 - WARNING - 第 82 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:17,651 - langgraph_use2 - INFO - 生成第 47 个用例，第 3 次尝试
2025-07-08 22:04:17,690 - langgraph_use2 - WARNING - 第 83 个测试点失败（第 2 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:17,690 - langgraph_use2 - INFO - 生成第 50 个用例，第 3 次尝试
2025-07-08 22:04:18,280 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:18,283 - langgraph_use2 - INFO -  第 38 个用例生成成功，用时 19.30s
2025-07-08 22:04:18,283 - langgraph_use2 - INFO - 生成第 56 个用例，第 3 次尝试
2025-07-08 22:04:19,781 - langgraph_use2 - WARNING - 第 4 个测试点失败（第 3 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProje
2025-07-08 22:04:19,781 - langgraph_use2 - INFO - 生成第 60 个用例，第 3 次尝试
2025-07-08 22:04:20,305 - langgraph_use2 - WARNING - 第 27 个测试点失败（第 3 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:20,305 - langgraph_use2 - INFO - 生成第 67 个用例，第 3 次尝试
2025-07-08 22:04:20,336 - langgraph_use2 - WARNING - 第 28 个测试点失败（第 3 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:20,337 - langgraph_use2 - INFO - 生成第 71 个用例，第 3 次尝试
2025-07-08 22:04:20,818 - langgraph_use2 - ERROR - 第 4 个用例多次失败，跳过: NoneType: None

2025-07-08 22:04:20,874 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:20,880 - langgraph_use2 - INFO -  第 81 个用例生成成功，用时 34.18s
2025-07-08 22:04:20,880 - langgraph_use2 - INFO - 生成第 64 个用例，第 3 次尝试
2025-07-08 22:04:21,318 - langgraph_use2 - ERROR - 第 27 个用例多次失败，跳过: NoneType: None

2025-07-08 22:04:21,350 - langgraph_use2 - ERROR - 第 28 个用例多次失败，跳过: NoneType: None

2025-07-08 22:04:22,413 - langgraph_use2 - WARNING - 第 56 个测试点失败（第 3 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:22,413 - langgraph_use2 - INFO - 生成第 69 个用例，第 3 次尝试
2025-07-08 22:04:22,601 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:22,608 - langgraph_use2 - INFO -  第 20 个用例生成成功，用时 24.59s
2025-07-08 22:04:22,608 - langgraph_use2 - INFO - 生成第 72 个用例，第 3 次尝试
2025-07-08 22:04:22,799 - langgraph_use2 - WARNING - 第 50 个测试点失败（第 3 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:22,799 - langgraph_use2 - INFO - 生成第 73 个用例，第 3 次尝试
2025-07-08 22:04:23,434 - langgraph_use2 - ERROR - 第 56 个用例多次失败，跳过: NoneType: None

2025-07-08 22:04:23,809 - langgraph_use2 - ERROR - 第 50 个用例多次失败，跳过: NoneType: None

2025-07-08 22:04:23,980 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:23,983 - langgraph_use2 - INFO -  第 39 个用例生成成功，用时 24.85s
2025-07-08 22:04:23,983 - langgraph_use2 - INFO - 生成第 76 个用例，第 3 次尝试
2025-07-08 22:04:24,159 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:24,161 - langgraph_use2 - INFO -  第 32 个用例生成成功，用时 23.12s
2025-07-08 22:04:24,161 - langgraph_use2 - INFO - 生成第 77 个用例，第 3 次尝试
2025-07-08 22:04:24,467 - langgraph_use2 - WARNING - 第 71 个测试点失败（第 3 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:24,467 - langgraph_use2 - INFO - 生成第 34 个用例，第 3 次尝试
2025-07-08 22:04:24,989 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:24,991 - langgraph_use2 - INFO -  第 45 个用例生成成功，用时 20.24s
2025-07-08 22:04:24,991 - langgraph_use2 - INFO - 生成第 82 个用例，第 3 次尝试
2025-07-08 22:04:25,137 - langgraph_use2 - WARNING - 第 64 个测试点失败（第 3 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:25,137 - langgraph_use2 - INFO - 生成第 83 个用例，第 3 次尝试
2025-07-08 22:04:25,196 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:25,201 - langgraph_use2 - INFO -  第 44 个用例生成成功，用时 17.85s
2025-07-08 22:04:25,477 - langgraph_use2 - ERROR - 第 71 个用例多次失败，跳过: NoneType: None

2025-07-08 22:04:26,145 - langgraph_use2 - ERROR - 第 64 个用例多次失败，跳过: NoneType: None

2025-07-08 22:04:26,322 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:26,324 - langgraph_use2 - INFO -  第 51 个用例生成成功，用时 20.46s
2025-07-08 22:04:26,592 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:26,594 - langgraph_use2 - INFO -  第 68 个用例生成成功，用时 17.17s
2025-07-08 22:04:26,942 - langgraph_use2 - WARNING - 第 73 个测试点失败（第 3 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:27,300 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:27,304 - langgraph_use2 - INFO -  第 18 个用例生成成功，用时 30.45s
2025-07-08 22:04:27,772 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:27,775 - langgraph_use2 - INFO -  第 37 个用例生成成功，用时 21.58s
2025-07-08 22:04:27,945 - langgraph_use2 - ERROR - 第 73 个用例多次失败，跳过: NoneType: None

2025-07-08 22:04:28,601 - langgraph_use2 - WARNING - 第 34 个测试点失败（第 3 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:28,805 - langgraph_use2 - WARNING - 第 48 个测试点失败（第 3 次）: 
Traceback (most recent call last):
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\pythonProject\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProj
2025-07-08 22:04:29,598 - langgraph_use2 - ERROR - 第 34 个用例多次失败，跳过: NoneType: None

2025-07-08 22:04:29,725 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:29,728 - langgraph_use2 - INFO -  第 40 个用例生成成功，用时 22.44s
2025-07-08 22:04:29,733 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:29,735 - langgraph_use2 - INFO -  第 2 个用例生成成功，用时 15.09s
2025-07-08 22:04:29,805 - langgraph_use2 - ERROR - 第 48 个用例多次失败，跳过: NoneType: None

2025-07-08 22:04:32,209 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:32,214 - langgraph_use2 - INFO -  第 84 个用例生成成功，用时 18.48s
2025-07-08 22:04:32,914 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:32,917 - langgraph_use2 - INFO -  第 1 个用例生成成功，用时 18.39s
2025-07-08 22:04:33,906 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:33,909 - langgraph_use2 - INFO -  第 88 个用例生成成功，用时 19.45s
2025-07-08 22:04:34,246 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:34,248 - langgraph_use2 - INFO -  第 16 个用例生成成功，用时 19.52s
2025-07-08 22:04:34,298 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:34,299 - langgraph_use2 - INFO -  第 47 个用例生成成功，用时 16.65s
2025-07-08 22:04:34,951 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:34,955 - langgraph_use2 - INFO -  第 23 个用例生成成功，用时 19.86s
2025-07-08 22:04:35,490 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:35,493 - langgraph_use2 - INFO -  第 36 个用例生成成功，用时 17.97s
2025-07-08 22:04:36,520 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:36,522 - langgraph_use2 - INFO -  第 49 个用例生成成功，用时 19.05s
2025-07-08 22:04:37,389 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:37,391 - langgraph_use2 - INFO -  第 59 个用例生成成功，用时 28.12s
2025-07-08 22:04:38,684 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:38,687 - langgraph_use2 - INFO -  第 60 个用例生成成功，用时 18.91s
2025-07-08 22:04:38,859 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:38,863 - langgraph_use2 - INFO -  第 72 个用例生成成功，用时 16.25s
2025-07-08 22:04:38,989 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:38,991 - langgraph_use2 - INFO -  第 25 个用例生成成功，用时 24.05s
2025-07-08 22:04:39,368 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:39,371 - langgraph_use2 - INFO -  第 43 个用例生成成功，用时 21.80s
2025-07-08 22:04:39,590 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:39,592 - langgraph_use2 - INFO -  第 76 个用例生成成功，用时 15.61s
2025-07-08 22:04:39,824 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:39,826 - langgraph_use2 - INFO -  第 85 个用例生成成功，用时 26.28s
2025-07-08 22:04:43,198 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:43,201 - langgraph_use2 - INFO -  第 67 个用例生成成功，用时 22.90s
2025-07-08 22:04:43,589 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:43,592 - langgraph_use2 - INFO -  第 82 个用例生成成功，用时 18.60s
2025-07-08 22:04:50,085 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:50,089 - langgraph_use2 - INFO -  第 77 个用例生成成功，用时 25.93s
2025-07-08 22:04:55,816 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:55,819 - langgraph_use2 - INFO -  第 83 个用例生成成功，用时 30.68s
2025-07-08 22:04:57,336 - httpx - INFO - HTTP Request: POST https://ark.cn-beijing.volces.com/api/v3/chat/completions "HTTP/1.1 200 OK"
2025-07-08 22:04:57,340 - langgraph_use2 - INFO -  第 69 个用例生成成功，用时 34.93s
2025-07-08 22:04:57,340 - langgraph_use2 - INFO - [Step 4] 用例生成完成: 成功 81 个，失败 10 个，用时 91.45s
2025-07-08 22:04:57,341 - langgraph_use2 - INFO - [Step 5] 校验测试用例，移除高度一致的重复项
2025-07-08 22:04:57,341 - langgraph_use2 - INFO - [Step 5] 校验完成：未发现重复用例
2025-07-08 22:04:57,341 - main - INFO - 生成测试用例成功，耗时 234.70 秒
2025-07-08 22:04:57,444 - uvicorn.error - INFO - Waiting for application shutdown.
2025-07-08 22:04:57,444 - uvicorn.error - INFO - Application shutdown complete.
2025-07-08 22:04:57,444 - uvicorn.error - INFO - Finished server process [20024]
